# ============================================================================
# Ablation Study: w/o Stage 2 (无第二阶段)
# Dataset: METR-LA (207 nodes)
# 消融目的: 测试第二阶段编码的贡献
# ============================================================================

# --------------------- Basic Information ---------------------
description: 'Ablation: Alternating ST Model without Stage 2'
model_name: 'AlternatingSTModel'
dataset_name: "METR-LA"
dataset_type: "Traffic speed"
mode: train

# --------------------- Device Configuration ---------------------
device: 'cuda'
gpu_num: 1

# --------------------- Dataset Configuration ---------------------
dataset_dir: 'datasets/'
adj_dir: 'datasets/METR-LA/adj_mx.pkl'
input_len: 12
output_len: 12
num_nodes: 207
use_timestamps: False
norm_each_channel: True
rescale: False
memmap: False
local: True

# --------------------- Training Configuration ---------------------
epochs: 100
batch_size: 32
lr: 0.001
weight_decay: 0.0005
eps: 0.001
evaluation_horizons: 12

# Learning Rate Scheduler
lr_patience: 10
lr_decay_factor: 0.5
min_lr: 0.000001  # 1e-6

# Gradient clipping
train:
    clip_grad_param:
        max_norm: 5.0
    null_val: 0.0

# --------------------- Feature Configuration ---------------------
in_channel: 1
froward_features: [0]
target_features: [0]

# --------------------- Core Architecture Parameters ---------------------
embed_dim: 64
dropout: 0.1
num_heads: 4
mlp_ratio: 4

# === 消融实验开关 ===
use_temporal_encoder: True   # ✅ 启用时间编码器
use_spatial_encoder: True    # ✅ 启用空间编码器
use_stage2: False            # ❌ 禁用第二阶段 (消融目标)

# Stage 1
temporal_depth_1: 2
spatial_depth_1: 2

# Decoder (不会被使用)
decoder_depth: 2
num_decoder_queries: 24

# Stage 2 (不会被使用)
temporal_depth_2: 2
spatial_depth_2: 2

# Fusion mechanism
fusion_type: 'cross_attn'

# Advanced features
use_positional_encoding: True
use_layer_norm: True

# --------------------- Denoise Settings ---------------------
use_denoising: True
denoise_type: 'conv'

# --------------------- Adaptive Graph Learning ---------------------
use_advanced_graph: True
graph_heads: 4
dim: 10
topK: 10

# --------------------- Evaluation Metrics ---------------------
metrics:
    MAE: "masked_mae"
    RMSE: "masked_rmse"
    MAPE: "masked_mape"

# --------------------- Optimization ---------------------
use_amp: False

# --------------------- Model Saving ---------------------
save_model: True
model_save_path: 'checkpoints/METR-LA_AlternatingST/ablation_wo_stage2/'

# --------------------- Logging Configuration ---------------------
test_mode: False
swanlab_mode: 'online'
log_dir: 'logs/METR-LA_AlternatingST/ablation_wo_stage2/'
