# ============ CPU Test Configuration ============ #

description: 'STGCN model test configuration for CPU'
model_name: 'STGCN'
dataset_name : "METR-LA"
dataset_type : "Traffic speed"
dataset_input_len : 12
dataset_output_len : 12
seq_len: 864
gpu_num : 0
device: 'cuda'
test_mode: True
swanlab_mode: disabled
mode: pretrain

pre_trained_path: 'checkpoints/PEMS03/checkpoint_0.pt'
preTrain_dataset_dir: 'datasets/PEMS03/data_in864_out12.pkl'
preTrain_dataset_index_dir: 'datasets/PEMS03/index_in864_out12.pkl'
preTrain_scaler_dir: 'datasets/PEMS03/scaler_in864_out12.pkl'

dataset_dir: 'datasets/PEMS03/data_in12_out12.pkl'
dataset_index_dir: 'datasets/PEMS03/index_in12_out12.pkl'
scaler_dir: 'datasets/PEMS03/scaler_in12_out12.pkl'
adj_dir: "datasets/PEMS03/adj_mx.pkl"

save_model: True
model_save_path: 'checkpoints/PEMS03/'
finetune_epochs: 1
pretrain_epochs: 1
adaptive: False
num_nodes: 358
n_vertex: 358
froward_features: [0]
target_features: [0]
lr: 0.01
momentum: 0.9
metrics: {"MAE": masked_mae, "RMSE": masked_rmse, "MAPE": masked_mape}

contrastive_weight: 0.05

evaluation_horizons : 12
preTrain_batch_size: 8
batch_size: 16
dim: 10
graph_heads: 4
topK: 10
patch_size: 12
in_channel: 1
embed_dim: 96
num_heads: 4
mlp_ratio: 4
dropout: 0.1
mask_ratio: 0.25
encoder_depth: 4
decoder_depth: 1

# ============ train ============ #
train:
    clip_grad_param:
        max_norm: 5.0
    num_epochs: 1
  
    epochs: 1
    null_val : 0.0

mask_args: {
                    "num_nodes": 358,
                    "dim": 10,
                    "topK": 6,
                    "adaptive": False,
                    "epochs": 20,
                    "patch_size": 12,
                    "in_channel": 1,
                    "embed_dim": 96,
                    "num_heads": 4,
                    "graph_heads": 4,
                    "mlp_ratio": 4,
                    "dropout": 0.1,
                    "mask_ratio": 0.25,
                    "encoder_depth": 4,
                    "decoder_depth": 1,
                    "mode": "forecasting"
    }

backend_args: {
                "num_nodes" : 358,
                "supports"  : '',
                "dropout"   : 0.3,
                "gcn_bool"  : True,
                "addaptadj" : True,
                "aptinit"   : null,
                "in_dim"    : 1,
                "out_dim"   : 12,
                "residual_channels" : 32,
                "dilation_channels" : 32,
                "skip_channels"     : 256,
                "end_channels"      : 512,
                "kernel_size"       : 2,
                "blocks"            : 4,
                "layers"            : 2
}