# ============================================================================
# AGPST Direct Forecasting Configuration
# Dataset: PEMS03
# Model: Simplified AGPST (No Patch Embedding)
# ============================================================================

# --------------------- Basic Information ---------------------
description: 'Direct Forecasting with Adaptive Graph Learning'
model_name: 'AGPST'
dataset_name: "PEMS03"
dataset_type: "Traffic speed"
mode: train

# --------------------- Device Configuration ---------------------
device: 'cuda'
gpu_num: 1

# --------------------- Dataset Configuration ---------------------
dataset_dir: 'datasets/'
adj_dir: 'datasets/PEMS03/adj_mx.pkl'
input_len: 12
output_len: 12
num_nodes: 358
use_timestamps: False
norm_each_channel: True
rescale: False
memmap: False
local: True

# --------------------- Training Configuration ---------------------
epochs: 100
batch_size: 64      # ⭐ 增大批次以稳定梯度
lr: 0.0003          # ⭐ 降低学习率 (Encoder-Decoder 需要更小lr)
evaluation_horizons: 12

# Gradient clipping
train:
    clip_grad_param:
        max_norm: 5.0
    null_val: 0.0

# --------------------- Model Architecture ---------------------
# Feature configuration
in_channel: 1
froward_features: [0]
target_features: [0]

# Denoising module
use_denoising: False  # Enable/disable denoising
denoise_type: 'conv'  # Options: 'conv' (lightweight) or 'attention' (powerful)

# Adaptive graph learning
use_advanced_graph: True  # Use advanced multi-scale graph learning
graph_heads: 4  # Number of graph attention heads (only for advanced graph)
dim: 10  # Node embedding dimension
topK: 10  # Top-K sparsification

# Time embedding
embed_dim: 96
dropout: 0.1

# Transformer encoder
encoder_depth: 4
num_heads: 4
mlp_ratio: 4

# Transformer decoder (Encoder-Decoder架构)
decoder_depth: 1  # ⭐ 减少到1层，降低过拟合风险

# Prediction head
pred_len: 12  # 预测长度

# --------------------- Evaluation Metrics ---------------------
metrics:
    MAE: "masked_mae"
    RMSE: "masked_rmse"
    MAPE: "masked_mape"

# --------------------- Model Saving ---------------------
save_model: True
model_save_path: 'checkpoints/PEMS03/'

# --------------------- Logging Configuration ---------------------
test_mode: False
swanlab_mode: 'online'

