# ============================================================================
# Alternating Spatio-Temporal Architecture - Phase 2 Optimized
# Dataset: PEMS03 (358 nodes)
# Model: AlternatingSTModel_Phase2
# Optimizations: Skip Connections + Parameter Sharing + Batch Processing
# ============================================================================

# --------------------- Basic Information ---------------------
description: 'Phase 2 Optimized Alternating ST Model with Skip Connections'
model_name: 'AlternatingSTModel_Phase2'
dataset_name: "PEMS03"
dataset_type: "Traffic speed"
mode: train

# --------------------- Device Configuration ---------------------
device: 'cuda'
gpu_num: 1

# --------------------- Dataset Configuration ---------------------
dataset_dir: 'datasets/'
adj_dir: 'datasets/PEMS03/adj_mx.pkl'
input_len: 12
output_len: 12
num_nodes: 358
use_timestamps: False
norm_each_channel: True
rescale: False
memmap: False
local: True

# --------------------- Training Configuration ---------------------
epochs: 100
batch_size: 32           
lr: 0.001  # PEMS datasets use standard lr (unlike METR-LA which needs 0.0005)
weight_decay: 0.0003
eps: 0.001
evaluation_horizons: 12

# Learning rate scheduler
scheduler:
    type: 'ReduceLROnPlateau'
    patience: 10
    factor: 0.5
    min_lr: 0.00001

# Gradient clipping
train:
    clip_grad_param:
        max_norm: 5.0
    null_val: 0.0

# --------------------- Phase 2 Architecture Configuration ---------------------
# Feature configuration
in_channel: 1
froward_features: [0]
target_features: [0]

# Core architecture parameters
embed_dim: 96  # Feature dimension
dropout: 0.05
num_heads: 4
mlp_ratio: 4

# Temporal and Spatial depth (simplified in Phase 2)
temporal_depth: 2  # Shared temporal encoder depth
spatial_depth: 2   # Shared spatial encoder depth

# Fusion mechanism
fusion_type: 'gated'  # Options: 'gated', 'concat', 'cross_attn'

# Advanced features
use_positional_encoding: True
use_layer_norm: True

# --------------------- Phase 2 Optimizations ---------------------
# Skip Connections: Multi-level residual connections
use_skip_connections: True
skip_connection_type: 'add'  # Options: 'add', 'concat'

# Parameter Sharing: Share encoders between Stage 1 and Stage 2
use_parameter_sharing: True  # Reduces ~40% parameters

# Batch Processing: Vectorized spatial encoding
batch_spatial_encoding: True  # ~30% speedup

# --------------------- Denoise Settings ---------------------
use_denoising: True  # Keep denoising for PEMS03 (more noisy than METR-LA)
denoise_type: 'conv'

# --------------------- Adaptive Graph Learning ---------------------
use_advanced_graph: True
graph_heads: 4
dim: 10
topK: 10

# --------------------- Evaluation Metrics ---------------------
metrics:
    MAE: "masked_mae"
    RMSE: "masked_rmse"
    MAPE: "masked_mape"

# --------------------- Optimization ---------------------
use_amp: False  # Automatic mixed precision

# --------------------- Model Saving ---------------------
save_model: True
model_save_path: 'checkpoints/PEMS03_AlternatingST_Phase2/'

# --------------------- Logging Configuration ---------------------
test_mode: False
swanlab_mode: 'online'
log_dir: 'logs/PEMS03_AlternatingST_Phase2/'

# --------------------- Phase 2 Improvements ---------------------
# Expected Results:
#   Phase 1 Baseline: MAE ~17-18
#   Phase 2 Target:   MAE ~15-16 (10-15% improvement)
# ============================================================================

