# ============ general ============ #

description: 'STGCN model configuration'
model_name: 'STGCN'
dataset_name : "METR-LA"
dataset_type : "Traffic speed"
dataset_input_len : 12
dataset_output_len : 12
gpu_num : 1
device: ''
preTrain_dataset_dir: 'datasets/PEMS03/data_in12_out12.pkl'
preTrain_dataset_index_dir: 'datasets/PEMS03/index_in12_out12.pkl'
preTrain_scaler_dir: 'datasets/PEMS03/scaler_in12_out12.pkl'
dataset_dir: 'datasets/METR-LA/data_in12_out12.pkl'
dataset_index_dir: 'datasets/METR-LA/index_in12_out12.pkl'
scaler_dir: 'datasets/METR-LA/scaler_in12_out12.pkl'
adj_dir: "datasets/PEMS03/adj_mx.pkl"
model_save_path: 'checkpoints/PEMS03/'
finetune_epochs: 100
pretrain_epochs: 10
adaptive: False
num_nodes: 358
n_vertex: 358
# mask_ratio: 0.5
froward_features: [0]
target_features: [0]
lr: 0.002
momentum: 0.9
metrics: {"MAE": masked_mae, "RMSE": masked_rmse, "MAPE": masked_mape}
Ks: 3
Kt: 3
blocks: [[3], [64, 16, 64], [64, 16, 64], [128, 128], [12]]
T: 12
act_func: 'glu'
graph_conv_type: 'graph_conv'
gso: ''
bias: True
droprate: 0.5
evaluation_horizons : 12
batch_size: 4
dim: 10
topK: 3
patch_size: 12
in_channel: 3
embed_dim: 96
num_heads: 4
mlp_ratio: 4
dropout: 0.1
mask_ratio: 0.25
encoder_depth: 4
decoder_depth: 1
# ============ train ============ #
train:
    clip_grad_param:
        max_norm: 5.0
    num_epochs: 100
  
    epochs: 100
    null_val : 0.0





