# ============================================================================
# AGPST Alternating Spatio-Temporal Architecture Configuration
# Dataset: PEMS08
# Model: AlternatingSTModel (Revolutionary Architecture!)
# ============================================================================

# --------------------- Basic Information ---------------------
description: 'Alternating Spatio-Temporal Encoding-Decoding Architecture'
model_name: 'AlternatingSTModel'
dataset_name: "PEMS08"
dataset_type: "Traffic speed"
mode: train

# --------------------- Device Configuration ---------------------
device: 'cuda'
gpu_num: 1

# --------------------- Dataset Configuration ---------------------
dataset_dir: 'datasets/'
adj_dir: 'datasets/PEMS08/adj_mx.pkl'
input_len: 12
output_len: 12
num_nodes: 170
use_timestamps: False
norm_each_channel: True
rescale: False
memmap: False
local: True

# --------------------- Training Configuration ---------------------
epochs: 100
batch_size: 32           
lr: 0.001              
weight_decay: 0.0001    
evaluation_horizons: 12

# Learning rate scheduler
scheduler:
    type: 'ReduceLROnPlateau'
    patience: 10
    factor: 0.5
    min_lr: 0.00001

# Gradient clipping
train:
    clip_grad_param:
        max_norm: 5.0
    null_val: 0.0

# --------------------- Model Architecture ---------------------
# Feature configuration
in_channel: 1
froward_features: [0]
target_features: [0]

# ============ Alternating Architecture Parameters ============

# Embedding
embed_dim: 96           # Feature dimension

# Stage 1: Primary feature extraction
temporal_depth_1: 2     # Number of layers in first temporal encoder
spatial_depth_1: 2      # Number of layers in first spatial encoder

# Stage 2: Deep feature refinement
temporal_depth_2: 2     # Number of layers in second temporal encoder
spatial_depth_2: 2      # Number of layers in second spatial encoder

# Attention
num_heads: 4            # Number of attention heads

# Fusion
fusion_type: 'gated'    # Fusion method: 'gated', 'concat', 'cross_attn'
                        # Recommended: gated (good performance + stability)

# Regularization
dropout: 0.05           # Dropout rate
# --------------------- Denoise Settings ---------------------
use_denoising: False  # Enable denoising for input data
denoise_type: 'conv'  # Options: 'conv', 'attention'
                       # 'conv': 1D convolutional denoiser (fast)
                       # 'attention': Attention-based denoiser (slower but effective)
                       # 'conv' is recommended for speed and effectiveness.
                       # 'attention' can be used for more complex scenarios.
   # Enable denoising module

# ============ Mixed Precision Training (Speed Optimization) ============
use_amp: False           # Automatic Mixed Precision training (30-50% speedup)

# ============ DataLoader Optimization (Speed Optimization) ============
dataloader:
    num_workers: 4          # Multi-process data loading
    pin_memory: True        # Pinned memory for GPU acceleration
    prefetch_factor: 2      # Data prefetching

# ============ Validation ============
val_interval: 1         # Validate every epoch
save_best_only: True    # Save only the best model

# ============ Output ============
checkpoints_dir: 'checkpoints/PEMS08_AlternatingST/'
log_dir: 'logs/PEMS08_AlternatingST/'

# ============ Loss Function ============
loss:
    type: 'masked_mae'  # Masked MAE
    null_val: 0.0

# ============ Optimizer ============
optimizer:
    type: 'Adam'
    lr: 0.0003
    weight_decay: 0.0001
    betas: [0.9, 0.999]
    eps: 1e-8

# ============ Metrics ============
metrics:
    - 'MAE'
    - 'RMSE'
    - 'MAPE'
