# PEMS03 Alternating ST Model - GCN Spatial Encoder (速度优先)

# 基于 Hybrid 配置,修改空间编码器为 GCN

# ============ 数据集配置 ============
dataset:
  name: 'PEMS03'
  data_path: 'datasets/PEMS03'
  num_nodes: 358

# ============ 模型配置 ============
model:
  num_nodes: 358
  in_steps: 12
  out_steps: 12
  input_dim: 1
  embed_dim: 96
  num_heads: 4
  
  temporal_depth_1: 2
  temporal_depth_2: 2
  
  # GCN 配置: 2 层 = 2-hop 邻域
  spatial_depth_1: 2  # 比 Hybrid 多一层 (因为没有 Transformer)
  spatial_depth_2: 2
  
  # === 核心: 使用 GCN ===
  spatial_encoder_type: 'gcn'
  
  fusion_type: 'gated'
  use_denoising: True
  denoise_type: 'conv'
  dropout: 0.05

# ============ 训练配置 ============
train:
  batch_size: 64
  epochs: 100
  optimizer: 'Adam'
  lr: 0.001
  weight_decay: 0.0005
  lr_patience: 10
  lr_decay_factor: 0.5
  min_lr: 1e-6
  early_stop_patience: 20
  loss: 'MAE'
  clip_grad: 1.0

val:
  batch_size: 64
  metrics: ['MAE', 'RMSE', 'MAPE']

log:
  save_dir: 'checkpoints/PEMS03_gcn'
  log_interval: 10
  val_interval: 1

misc:
  seed: 42
  num_workers: 4
  device: 'cuda'
